swagger: "2.0"
info:
  description: "Aplicação para avaliação de crédito"
  version: "1.0.0"
  title: "Swagger Avaliacao"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "http"
paths:
  /clientes/cliente:
    post:
      tags:
      - "avaliacao"
      summary: "Cria um cadastro de cliente"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        201:
          description: "Created"

    get:
      tags:
      - "avaliacao"
      summary: "Retorna todos os clientes"
      description: ""
      operationId: "getCliente"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ClienteId"
  
  /clientes/cliente/{id}:
    get:
      tags:
      - "avaliacao"
      summary: "retorna um cadastro de  com base no ID"
      description: ""
      operationId: "getCliente por id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        required: true
        type: "integer"
        in: "path"
        description: "Identificador do banco de dados. "
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ClienteId"
        400:
          description: "não encontrado"
    delete:
      tags:
      - "avaliacao"
      summary: "Exclui um cadastro de cliente"
      description: ""
      operationId: "delete por id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        required: true
        type: "integer"
        in: "path"
        description: "Identificador do banco de dados. "
      responses:
        200:
          description: "successful operation"
        400:
          description: "não encontrado"

securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
   Cliente:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      nome:
        type: "string"
        example: "Jose Joao da Silva"        
      cpf:
        type: "string"
        example: "000.000.000-00"
      idade:
        type: "integer"
        example: 33
      sexo:
        type: "string"
        enum:
        - "M"
        - "F"
      estacoCivil:
        type: "string"
        enum:
        - "Casado"
        - "Solteiro"
        - "Viúvo"
        - "Divorciado"
      estado:
        type: "string"
      dependentes:
        type: "integer"
      renda:
        type: "number"
        format: "double"
   ClienteId:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
      nome:
        type: "string"
        example: "Jose Joao da Silva"  
      cpf:
        type: "string"
        example: "000.000.000-00"
      idade:
        type: "integer"
        example: 33
      sexo:
        type: "string"
        enum:
        - "M"
        - "F"
      estacoCivil:
        type: "string"
        enum:
        - "Casado"
        - "Solteiro"
        - "Viúvo"
        - "Divorciado"
      estado:
        type: "string"
      dependentes:
        type: "integer"
      renda:
        type: "number"
        format: "double"        
    xml:
      name: "Pet"
